{{- range .Values.databases }}
{{- $dbOwner := default .name .owner }}
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: {{ include "cluster.fullname" $ }}-{{ .name | replace "_" "-" }}
  namespace: {{ include "cluster.namespace" $ }}
  {{- with $.Values.cluster.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
  {{- include "cluster.labels" $ | nindent 4 }}
  {{- with $.Values.cluster.additionalLabels }}
    {{ toYaml . | nindent 4 }}
  {{- end }}
spec:
  name: {{ .name }}
  cluster:
    name: {{ include "cluster.fullname" $ }}
  ensure: {{ .ensure | default "present" }}
  owner: {{ $dbOwner }}
  template: {{ .template | default "template1" }}
  encoding: {{ .encoding | default "UTF8" }}
  databaseReclaimPolicy: {{ .databaseReclaimPolicy | default "retain" }}
  {{- if hasKey . "isTemplate" }}
  isTemplate: {{ .isTemplate }}
  {{- end }}
  {{- if hasKey . "allowConnections" }}
  allowConnections: {{ .allowConnections }}
  {{- end }}
  {{- if hasKey . "connectionLimit" }}
  connectionLimit: {{ .connectionLimit }}
  {{- end }}
  {{- with .tablespace }}
  tablespace: {{ . }}
  {{- end }}
  {{- with .locale }}
  locale: {{ . }}
  {{- end }}
  {{- with .localeProvider }}
  localeProvider: {{ . }}
  {{- end }}
  {{- with .localeCollate }}
  localeCollate: {{ . }}
  {{- end }}
  {{- with .localeCType }}
  localeCType: {{ . }}
  {{- end }}
  {{- with .icuLocale }}
  icuLocale: {{ . }}
  {{- end }}
  {{- with .icuRules }}
  icuRules: {{ . }}
  {{- end }}
  {{- with .builtinLocale }}
  builtinLocale: {{ . }}
  {{- end }}
  {{- with .collationVersion }}
  collationVersion: {{ . | quote }}
  {{- end }}
  {{- with .schemas }}
  schemas:
  {{- range . }}
    - name: {{ .name }}
      owner: {{ default $dbOwner .owner }}
      ensure: {{ .ensure | default "present" }}
  {{- end }}
  {{- end }}
  {{- with .extensions }}
  extensions:
  {{- range . }}
    {{- $extname := .name }}
    - name: {{ .name }}
      {{- if eq $extname "pg_search" }}
      version: {{ $.Values.version.paradedb | quote }}
      {{- else if not (empty .version) }}
      version: {{ .version | quote }}
      {{- end }}
      {{- with .schema }}
      schema: {{ . }}
      {{- end }}
      ensure: {{ .ensure | default "present" }}
  {{- end }}
  {{- end }}
{{- end }}
