{{- if and (eq .Values.mode "replica" ) (not (empty .Values.replica.origin.pg_basebackup.host)) .Values.replica.origin.pg_basebackup.passwordSecret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ default (printf "%s-origin-pg-basebackup-password" (include "cluster.fullname" .)) .Values.replica.origin.pg_basebackup.passwordSecret.name }}
  namespace: {{ include "cluster.namespace" . }}
data:
  {{ .Values.replica.origin.pg_basebackup.passwordSecret.key }}: {{ required ".Values.replica.origin.pg_basebackup.passwordSecret.value required when creating a password secret." .Values.replica.origin.pg_basebackup.passwordSecret.value | b64enc | quote }}
{{- end }}
