{{- range .Values.poolers }}
{{- if .monitoring }}
{{- if .monitoring.enabled }}
{{- if .monitoring.podMonitor }}
{{- if .monitoring.podMonitor.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "cluster.fullname" $ }}-pooler-{{ .name }}-podmonitor
  namespace: {{ include "cluster.namespace" $ }}
  labels:
    cnpg.io/cluster: {{ include "cluster.fullname" $ }}
    cnpg.io/poolerName: {{ include "cluster.fullname" $  }}-pooler-{{ .name }}
    {{- include "cluster.labels" $ | nindent 4 }}
    {{- with $.Values.cluster.monitoring.podMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with $.Values.cluster.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      cnpg.io/cluster: {{ include "cluster.fullname" $ }}
      cnpg.io/podRole: pooler
      cnpg.io/poolerName: {{ include "cluster.fullname" $  }}-pooler-{{ .name }}
  podMetricsEndpoints:
    - port: metrics
      {{- with .monitoring.podMonitor.relabelings }}
      relabelings:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .monitoring.podMonitor.metricRelabelings }}
      metricRelabelings:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
