name: Verifies that a CNPG cluster has a certain amount of ready instances
description: Verifies that a CNPG cluster has a certain amount of ready instances
inputs:
  cluster-name:
    description: The name of the cluster to verify
    required: true
    default: database-cluster
  namespace:
    description: 'The name of the namespace where the Cluster is deployed'
    required: false
    default: 'default'
  ready-instances:
    description: The amount of ready instances to wait for
    required: true
    default: "3"

runs:
  using: composite
  steps:
    - name: Wait for the cluster to become ready
      shell: bash
      env:
        CLUSTER_NAME: ${{ inputs.cluster-name }}
        NAMESPACE: ${{ inputs.namespace }}
        EXPECTED_READY_INSTANCES: ${{ inputs.ready-instances }}
      run: |
        ITER=0
        while true; do
          if [[ $ITER -ge 300 ]]; then
            echo "Cluster not ready"
            exit 1
          fi
          READY_INSTANCES=$(kubectl get clusters.postgresql.cnpg.io $CLUSTER_NAME -n $NAMESPACE -o jsonpath='{.status.readyInstances}')
          if [[ "$READY_INSTANCES" == "$EXPECTED_READY_INSTANCES" ]]; then
            echo "Cluster up and running"
            break
          fi
          sleep 1
          (( ++ITER ))
        done
