mode: replica

cluster:
  instances: 1

replica:
  topology: distributed
  topologySettings:
    distributed:
      primary: false

recovery:
  method: objectStorage
  clusterName: database-clustermarket-euw1
  provider: s3
  s3:
    region: eu-west-1
    bucket: euw1-db-backups
    path: /v1-restore
    accessKey: "AWS_S3_ACCESS_KEY"
    secretKey: "AWS_S3_SECRET_KEY"

backups:
  objectStorage:
    provider: s3
    providerSettings:
      s3:
        region: eu-central-1
        bucket: euc1-db-backups
        path: /v1-restore
        accessKey: "AWS_S3_ACCESS_KEY"
        secretKey: "AWS_S3_SECRET_KEY"
  scheduledBackups:
    - name: daily-backup # Daily at midnight
      schedule: "0 0 0 * * *" # Daily at midnight
      backupOwnerReference: self
  retentionPolicy: 30d
