name: Feature request
description: Suggest an idea for this project
title: "[Chart name: Cluster, CNPG, etc.] Issue Title"
labels: [enhancement]
assignees:
  -
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: textarea
    id: desc
    attributes:
      label: Is your feature request related to a problem ?
      description: Give a clear and concise description of what need to be enhanced.
      placeholder:  ex. The [...] part is missing [...]
    validations:
      required: true

  - type: textarea
    id: prop-solution
    attributes:
      label: Describe the solution you'd like.
      description: A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered.
      description: A clear and concise description of any alternative solutions or features you've considered. If nothing, please enter `NONE`
    validations:
      required: true

  - type: textarea
    id: additional-ctxt
    attributes:
      label: Additional context.
      description: Add any other context or screenshots about the feature request here.
    validations:
      required: false
