{{- $alert := "CNPGClusterBackupFailed" -}}
{{- if not (has $alert .excludeRules) -}}
alert: {{ $alert }}
annotations:
  summary: CNPG Cluster backup has failed.
  description: |-
    Backup for CloudNativePG Cluster "{{ .namespace }}/{{ .cluster }}" has failed.
expr: |
  sum by (namespace) (cnpg_collector_last_failed_backup_timestamp{namespace="{{ .namespace }}", pod=~"{{ .podSelector }}"})
  >
  sum by (namespace) (cnpg_collector_last_available_backup_timestamp{namespace="{{ .namespace }}", pod=~"{{ .podSelector }}"})
for: 5m
labels:
  severity: warning
  namespace: {{ .namespace }}
  cnpg_cluster: {{ .cluster }}
{{- end -}}
