name: Deploy the CNPG Operator
description: Deploys the CNPG Operator to a Kubernetes cluster
inputs:
  namespace:
    description: 'The name of the namespace where the operator will be deployed'
    required: false
    default: 'cnpg-system'
  cluster-wide:
    description: 'If the operator should be deployed cluster-wide or in single-namespace mode'
    required: false
    default: 'true'
runs:
  using: composite
  steps:
    - name: Deploy the operator
      shell: bash
      env:
        NAMESPACE: ${{ inputs.namespace }}
        CLUSTER_WIDE: ${{ inputs.cluster-wide }}
      run: |
        helm repo add cnpg https://cloudnative-pg.github.io/charts
        helm upgrade \
          --install \
          --namespace $NAMESPACE \
          --create-namespace \
          --set config.clusterWide=$CLUSTER_WIDE \
          --wait \
          cnpg cnpg/cloudnative-pg
