name: Deploy the CNPG Operator
description: Deploys the CNPG Operator to a Kubernetes cluster
runs:
  using: composite
  steps:
    - name: Deploy the operator
      shell: bash
      run:
        helm repo add cnpg https://cloudnative-pg.github.io/charts

        helm upgrade
        --install 
        --namespace cnpg-system
        --create-namespace
        --wait
        cnpg cnpg/cloudnative-pg
