type: postgresql
mode: recovery

recovery:
  method: object_store
  clusterName: "cluster-name-to-recover-from"
  provider: s3
  s3:
    region: "eu-west-1"
    bucket: "db-backups"
    path: "/v1-restore"
    accessKey: "AWS_S3_ACCESS_KEY"
    secretKey: "AWS_S3_SECRET_KEY"

cluster:
  instances: 1

backups:
  endpointURL: "https://cm-db-chart-test.ams3.digitaloceanspaces.com"
  provider: s3
  s3:
    region: "eu-west-1"
    bucket: "db-backups"
    path: "/v1-restore"
    accessKey: "AWS_S3_ACCESS_KEY"
    secretKey: "AWS_S3_SECRET_KEY"
  scheduledBackups:
    - name: daily-backup # Daily at midnight
      schedule: "0 0 0 * * *" # Daily at midnight
      backupOwnerReference: self
  retentionPolicy: "30d"
