{{- if and .Values.barmanCloudPlugin.enabled (not .Values.barmanCloudPlugin.s3.inheritFromIAMRole) .Values.barmanCloudPlugin.s3.externalSecret.enabled }}
{{- $secretName := include "cluster.barmanCloudPlugin.secretName" . -}}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ default (printf "%s-external-secret" $secretName) .Values.barmanCloudPlugin.s3.externalSecret.name }}
  namespace: {{ include "cluster.namespace" . }}
  labels:
  {{- include "cluster.labels" . | nindent 4 }}
  {{- with .Values.barmanCloudPlugin.s3.externalSecret.labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.barmanCloudPlugin.s3.externalSecret.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  data:
    - remoteRef:
        conversionStrategy: {{ .Values.barmanCloudPlugin.s3.externalSecret.remoteRefs.accessKeyId.conversionStrategy }}
        decodingStrategy: {{ .Values.barmanCloudPlugin.s3.externalSecret.remoteRefs.accessKeyId.decodingStrategy }}
        key: {{ required ".Values.barmanCloudPlugin.s3.externalSecret.remoteRefs.accessKeyId.key is required when barmanCloudPlugin.s3.externalSecret.enabled is true." .Values.barmanCloudPlugin.s3.externalSecret.remoteRefs.accessKeyId.key }}
        metadataPolicy: {{ .Values.barmanCloudPlugin.s3.externalSecret.remoteRefs.accessKeyId.metadataPolicy }}
        property: {{ required ".Values.barmanCloudPlugin.s3.externalSecret.remoteRefs.accessKeyId.property is required when barmanCloudPlugin.s3.externalSecret.enabled is true." .Values.barmanCloudPlugin.s3.externalSecret.remoteRefs.accessKeyId.property }}
      secretKey: {{ .Values.barmanCloudPlugin.s3.secret.accessKeyIdKey }}
    - remoteRef:
        conversionStrategy: {{ .Values.barmanCloudPlugin.s3.externalSecret.remoteRefs.secretAccessKey.conversionStrategy }}
        decodingStrategy: {{ .Values.barmanCloudPlugin.s3.externalSecret.remoteRefs.secretAccessKey.decodingStrategy }}
        key: {{ required ".Values.barmanCloudPlugin.s3.externalSecret.remoteRefs.secretAccessKey.key is required when barmanCloudPlugin.s3.externalSecret.enabled is true." .Values.barmanCloudPlugin.s3.externalSecret.remoteRefs.secretAccessKey.key }}
        metadataPolicy: {{ .Values.barmanCloudPlugin.s3.externalSecret.remoteRefs.secretAccessKey.metadataPolicy }}
        property: {{ required ".Values.barmanCloudPlugin.s3.externalSecret.remoteRefs.secretAccessKey.property is required when barmanCloudPlugin.s3.externalSecret.enabled is true." .Values.barmanCloudPlugin.s3.externalSecret.remoteRefs.secretAccessKey.property }}
      secretKey: {{ .Values.barmanCloudPlugin.s3.secret.secretAccessKeyKey }}
  refreshInterval: {{ .Values.barmanCloudPlugin.s3.externalSecret.refreshInterval }}
  secretStoreRef:
    kind: {{ required ".Values.barmanCloudPlugin.s3.externalSecret.secretStoreRef.kind is required when barmanCloudPlugin.s3.externalSecret.enabled is true." .Values.barmanCloudPlugin.s3.externalSecret.secretStoreRef.kind }}
    name: {{ required ".Values.barmanCloudPlugin.s3.externalSecret.secretStoreRef.name is required when barmanCloudPlugin.s3.externalSecret.enabled is true." .Values.barmanCloudPlugin.s3.externalSecret.secretStoreRef.name }}
  target:
    creationPolicy: {{ .Values.barmanCloudPlugin.s3.externalSecret.target.creationPolicy }}
    deletionPolicy: {{ .Values.barmanCloudPlugin.s3.externalSecret.target.deletionPolicy }}
    name: {{ default $secretName .Values.barmanCloudPlugin.s3.externalSecret.target.name }}
{{- end }}
