{{- if .Values.barmanCloudPlugin.enabled }}
{{ $context := . -}}
{{ range .Values.barmanCloudPlugin.scheduledBackups -}}
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: {{ include "cluster.fullname" $context }}-{{ .name }}
  namespace: {{ include "cluster.namespace" $ }}
  labels:
  {{- include "cluster.labels" $context | nindent 4 }}
spec:
  immediate: true
  schedule: {{ .schedule | quote }}
  method: plugin
  pluginConfiguration:
    name: {{ default $context.Values.barmanCloudPlugin.pluginName .pluginName }}
  backupOwnerReference: {{ .backupOwnerReference }}
  cluster:
    name: {{ include "cluster.fullname" $context }}
{{ end -}}
{{ end }}
