{{ if and .Values.imageCatalog.create (not (empty .Values.imageCatalog.images )) }}
apiVersion: postgresql.cnpg.io/v1
kind: ImageCatalog
metadata:
  name: {{ include "cluster.fullname" . }}
  namespace: {{ include "cluster.namespace" . }}
spec:
  images:
    {{- range $image := .Values.imageCatalog.images }}
    - image: {{ $image.image }}
      major: {{ $image.major }}
    {{- end }}
{{- end }}
