{{- if eq (include "cluster.useTimescaleDBDefaults" .) "true" -}}
apiVersion: postgresql.cnpg.io/v1
kind: ImageCatalog
metadata:
  name: {{ include "cluster.fullname" . }}-timescaledb-ha
  namespace: {{ include "cluster.namespace" . }}
  labels:
    cnpg.io/cluster: {{ include "cluster.fullname" . }}
    {{- include "cluster.labels" . | nindent 4 }}
spec:
  images:
    - major: 12
      image: timescale/timescaledb-ha:pg12-ts{{ .Values.version.timescaledb }}
    - major: 13
      image: timescale/timescaledb-ha:pg13-ts{{ .Values.version.timescaledb }}
    - major: 14
      image: timescale/timescaledb-ha:pg14-ts{{ .Values.version.timescaledb }}
    - major: 15
      image: timescale/timescaledb-ha:pg15-ts{{ .Values.version.timescaledb }}
    - major: 16
      image: timescale/timescaledb-ha:pg16-ts{{ .Values.version.timescaledb }}
    - major: 17
      image: timescale/timescaledb-ha:pg17-ts{{ .Values.version.timescaledb }}
    - major: 18
      image: timescale/timescaledb-ha:pg18-ts{{ .Values.version.timescaledb }}
{{ end }}
