{{ if .Values.backups.enabled }}
{{ $context := . -}}
{{ range .Values.backups.scheduledBackups -}}
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: {{ include "cluster.fullname" $context  }}-{{ .name }}
  namespace: {{ include "cluster.namespace" $ }}
  labels: {{ include "cluster.labels" $context | nindent 4 }}
spec:
  immediate: {{ default true .immediate }}
  schedule: {{ .schedule | quote }}
  method: {{ .method }}
  backupOwnerReference: {{ .backupOwnerReference }}
  cluster:
    name: {{ include "cluster.fullname" $context }}
{{ end -}}
{{ end }}
