{{ if .Values.backups.enabled }}
{{ $context := . -}}
{{ range .Values.backups.scheduledBackups -}}
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: {{ include "cluster.fullname" .  }}-{{ .name }}
  labels:
    {{ include "cluster.labels" $context | nindent 4 }}
spec:
  schedule: {{ .schedule }}
  backupOwnerReference: {{ .backupOwnerReference }}
  cluster:
    name: {{ include "cluster.fullname" . }}
{{ end -}}
{{ end }}
