{{ if .Values.backups.enabled }}
{{ $context := . -}}
{{ range .Values.backups.scheduledBackups -}}
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: {{ include "cluster.fullname" $context  }}-{{ .name }}
  namespace: {{ include "cluster.namespace" $ }}
  labels: {{ include "cluster.labels" $context | nindent 4 }}
spec:
  immediate: true
  schedule: {{ .schedule | quote }}
  backupOwnerReference: {{ .backupOwnerReference }}
  cluster:
    name: {{ include "cluster.fullname" $context }}
{{- if (eq (include "cluster.useBarmanCloudPlugin" $context ) "true") }}
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
  method: plugin
{{ else }}
  method: {{ .method }}
{{- end }}
{{ end -}}
{{ end }}
