{{- if not (empty .Values.cluster.monitoring.customQueries) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cluster.fullname" . }}-monitoring
  namespace: {{ include "cluster.namespace" . }}
  labels:
    cnpg.io/reload: ""
    {{- include "cluster.labels" . | nindent 4 }}
data:
  custom-queries: |
    {{- range .Values.cluster.monitoring.customQueries }}
    {{ .name }}: {{ omit . "name" | toYaml | nindent 6 }}
    {{- end }}
{{- end }}
