name: Verifies that a CNPG cluster has a certain amount of ready instances

on:
  workflow_call:
    inputs:
      cluster-name:
        description: The name of the cluster to verify
        required: true
        default: database-cluster
      ready-instances:
        description: The amount of ready instances to wait for
        required: true
        default: 3

jobs:
  verify-ready-instances:
    runs-on: ubuntu-22.04
    steps:
      - name: Wait for cluster to become ready
        run: |
          ITER=0
          while true; do
            if [[ $ITER -ge 300 ]]; then
              echo "Cluster not ready"
              exit 1
            fi
            READY_INSTANCES=$(kubectl get cluster ${INPUT_CLUSTER_NAME} -o jsonpath='{{.status.readyInstances}}')
            if [[ "$READY_INSTANCES" == ${INPUT_READY_INSTANCES} ]]; then
              echo "Cluster up and running"
              break
            fi
            sleep 1
            (( ++ITER ))
          done
