{
 "title": "ParadeDB",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   {
    "name": "operatorNamespace",
    "label": "Operator Namespace",
    "query": {
     "query": "label_values(controller_runtime_webhook_requests_total{webhook=\"/mutate-postgresql-cnpg-io-v1-cluster\"},namespace)"
    }
   },
   { "name": "namespace", "label": "Database Namespace", "query": { "query": "cnpg_collector_up" } },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "cnpg_collector_up{namespace=~\"$namespace\"}"
    }
   },
   {
    "name": "instances",
    "label": "Instances",
    "query": {
     "query": "cnpg_collector_up{namespace=~\"$namespace\",pod=~\"$cluster-([1-9][0-9]*)$\"}"
    }
   },
   {
    "name": "bm25_indicies",
    "query": {
     "query": "label_values(cnpg_paradedb_index_layer_segments_bucket{namespace=\"$namespace\"},relname)"
    }
   },
   {
    "name": "nodes",
    "query": {
     "query": "label_values(kube_node_info,node)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Alerts", "type": "alertlist", "gridPos": { "h": 12, "w": 5, "x": 0, "y": 0 } },
  { "title": "Health", "type": "text", "gridPos": { "h": 1, "w": 4, "x": 5, "y": 0 } },
  { "title": "Overview", "type": "text", "gridPos": { "h": 1, "w": 9, "x": 9, "y": 0 } },
  { "title": "Storage", "type": "text", "gridPos": { "h": 1, "w": 3, "x": 18, "y": 0 } },
  { "title": "Backups", "type": "text", "gridPos": { "h": 1, "w": 3, "x": 21, "y": 0 } },
  {
   "type": "stat",
   "description": "Cluster Replication Health represents the availability of replica servers available to replace the primary in case of a failure.",
   "gridPos": { "h": 2, "w": 2, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(max(count by (pod) (cnpg_pg_stat_replication_backend_start{namespace=\"$namespace\", job=\"$namespace/$cluster\",application_name=~\"$instances\"})) - sum(cnpg_pg_replication_is_wal_receiver_up{namespace=~\"$namespace\", pod=~\"$instances\"})) + (clamp_max(max(cnpg_pg_replication_streaming_replicas{namespace=~\"$namespace\", pod=~\"$instances\"}), 1) - 1)",
     "legendFormat": "Replication"
    }
   ]
  },
  {
   "type": "stat",
   "description": "High lag indicates issue with replication. Network or storage interfaces may not have enough bandwidth to handle incoming traffic and replication at the same time.",
   "gridPos": { "h": 2, "w": 1, "x": 7, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(cnpg_pg_replication_lag{namespace=~\"$namespace\",pod=~\"$instances\"}) + max(cnpg_pg_stat_replication_write_lag_seconds{namespace=~\"$namespace\",pod=~\"$instances\"}) + max(cnpg_pg_stat_replication_flush_lag_seconds{namespace=~\"$namespace\",pod=~\"$instances\"}) + max(cnpg_pg_stat_replication_replay_lag_seconds{namespace=~\"$namespace\",pod=~\"$instances\"})",
     "legendFormat": "Lag"
    },
    {}
   ]
  },
  {
   "type": "stat",
   "description": "Low disk space or low inode count will result in data loss.",
   "gridPos": { "h": 2, "w": 1, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max((max(max by(persistentvolumeclaim) (1 - kubelet_volume_stats_available_bytes{namespace=\"$namespace\", persistentvolumeclaim=~\"$instances\"} / kubelet_volume_stats_capacity_bytes{namespace=\"$namespace\", persistentvolumeclaim=~\"$instances\"}))) OR (max by(persistentvolumeclaim) (kubelet_volume_stats_inodes_used{namespace=\"$namespace\", persistentvolumeclaim=~\"$instances\"} / kubelet_volume_stats_inodes{namespace=\"$namespace\", persistentvolumeclaim=~\"$instances\"})))",
     "legendFormat": "Storage"
    }
   ]
  },
  {
   "title": "Last failover",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(cnpg_pg_postmaster_start_time{namespace=~\"$namespace\",pod=~\"$instances\"})*1000"
    }
   ]
  },
  {
   "title": "TPS",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 11, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(cnpg_pg_stat_database_xact_commit{namespace=~\"$namespace\",pod=~\"$instances\"}[$__interval])) + sum(rate(cnpg_pg_stat_database_xact_rollback{namespace=~\"$namespace\",pod=~\"$instances\"}[$__interval]))",
     "legendFormat": "TPS"
    }
   ]
  },
  {
   "title": "CPU Utilisation",
   "type": "gauge",
   "description": "CPU Utilisation from Requests",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$namespace\", pod=~\"$instances\"}) / sum(kube_pod_container_resource_requests{job=\"kube-state-metrics\",  namespace=\"$namespace\", resource=\"cpu\", pod=~\"$instances\"})"
    }
   ]
  },
  {
   "title": "Memory Utilisation",
   "type": "gauge",
   "description": "Memory Utilisation from Requests",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"$namespace\",container!=\"\", image!=\"\", pod=~\"$instances\"}) / sum(max by(pod) (kube_pod_container_resource_requests{job=\"kube-state-metrics\", namespace=\"$namespace\", resource=\"memory\", pod=~\"$instances\"}))"
    }
   ]
  },
  {
   "title": "Volume Space Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(max by(persistentvolumeclaim) (1 - kubelet_volume_stats_available_bytes{namespace=\"$namespace\", persistentvolumeclaim=~\"$instances\"} / kubelet_volume_stats_capacity_bytes{namespace=\"$namespace\", persistentvolumeclaim=~\"$instances\"}))",
     "legendFormat": "DATA"
    },
    {
     "expr": "max(max by(persistentvolumeclaim) (1 - kubelet_volume_stats_available_bytes{namespace=\"$namespace\", persistentvolumeclaim=~\"(${instances})-wal\"} / kubelet_volume_stats_capacity_bytes{namespace=\"$namespace\", persistentvolumeclaim=~\"(${instances})-wal\"}))",
     "legendFormat": "WAL"
    },
    {
     "expr": "max(\n    sum by (namespace,persistentvolumeclaim) (kubelet_volume_stats_used_bytes{namespace=\"$namespace\", persistentvolumeclaim=~\"(${instances})-tbs.*\"}) \n    /\n    sum by (namespace,persistentvolumeclaim) (kubelet_volume_stats_capacity_bytes{namespace=\"$namespace\", persistentvolumeclaim=~\"(${instances})-tbs.*\"}) \n    *\n    on(namespace, persistentvolumeclaim) group_left(volume)\n    kube_pod_spec_volumes_persistentvolumeclaims_info{pod=~\"$instances\"}\n)",
     "legendFormat": "Tablespaces (max)"
    }
   ]
  },
  {
   "title": "Last Base Backup",
   "type": "stat",
   "description": "Elapsed time since the last successful base backup.",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "-(time() - max(cnpg_collector_last_available_backup_timestamp{namespace=\"$namespace\",pod=~\"$instances\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "description": "High resource usage (CPU, Memory, DB Connections)",
   "gridPos": { "h": 2, "w": 4, "x": 5, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{ namespace=\"$namespace\", pod=~\"$instances\"}) / sum(kube_pod_container_resource_requests{job=\"kube-state-metrics\", namespace=\"$namespace\", resource=\"cpu\", pod=~\"$instances\"}))",
     "legendFormat": "CPU"
    },
    {
     "expr": "(sum(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"$namespace\",container!=\"\", image!=\"\", pod=~\"$instances\"}) / sum(max by(pod) (kube_pod_container_resource_requests{job=\"kube-state-metrics\", namespace=\"$namespace\", resource=\"memory\", pod=~\"$instances\"})))",
     "legendFormat": "Memory"
    },
    {
     "expr": " (max(sum by (pod) (cnpg_backends_total{namespace=~\"$namespace\", pod=~\"$instances\"}) / sum by (pod) (cnpg_pg_settings_setting{name=\"max_connections\", namespace=~\"$namespace\", pod=~\"$instances\"})))",
     "legendFormat": "Connections"
    }
   ]
  },
  {
   "title": "Last archived WAL",
   "type": "stat",
   "description": "Computes the time since the last known WAL archival in the primary.\nWe ensure to ignore the metric in the replicas by using (1 - cnpg_pg_replication_in_recovery ) as a multiplicative factor. It will be 0 for replicas, 1 for the primary.",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max((1 - cnpg_pg_replication_in_recovery{namespace=~\"$namespace\",pod=~\"$instances\"}) * (time() - timestamp(cnpg_pg_stat_archiver_seconds_since_last_archival{namespace=~\"$namespace\",pod=~\"$instances\"}) +\ncnpg_pg_stat_archiver_seconds_since_last_archival{namespace=~\"$namespace\",pod=~\"$instances\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 9, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cnpg_collector_postgres_version{namespace=~\"$namespace\",pod=~\"$instances\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Base Backups are considered healthy when there has been at least one base backup in the last 24 hours.",
   "gridPos": { "h": 2, "w": 1, "x": 5, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - max(cnpg_collector_last_available_backup_timestamp{namespace=\"$namespace\", pod=~\"$instances\"})",
     "legendFormat": "Backups"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Base Backups are considered healthy when there has been at least one base backup in the last 24 hours.",
   "gridPos": { "h": 2, "w": 1, "x": 6, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max((1 - cnpg_pg_replication_in_recovery{namespace=~\"$namespace\", pod=~\"$instances\"}) * (time() - timestamp(cnpg_pg_stat_archiver_seconds_since_last_archival{namespace=~\"$namespace\", pod=~\"$instances\"}) +\ncnpg_pg_stat_archiver_seconds_since_last_archival{namespace=~\"$namespace\", pod=~\"$instances\"}))",
     "legendFormat": "WAL"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Online if there is at least one ready operator pod",
   "gridPos": { "h": 2, "w": 1, "x": 7, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_ready{namespace=\"$operatorNamespace\", pod=~\"cloudnative-pg-operator.+\", condition=\"true\"})",
     "legendFormat": "Operator Status"
    }
   ]
  },
  {
   "type": "stat",
   "description": "The operator reconcile errors don't distinguish between database cluster or namespaces.",
   "gridPos": { "h": 2, "w": 1, "x": 8, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "$RECONCILE_ERRORS_BACKUP + $RECONCILE_ERRORS_CLUSTER * 10 + $RECONCILE_ERRORS_POOLER * 100 + $RECONCILE_ERRORS_SCHEDULED_BACKUP * 1000",
     "type": "math"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 14, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$namespace\", pod=~\"$instances\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Container memory working set",
   "gridPos": { "h": 2, "w": 2, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{pod=~\"$instances\", namespace=\"$namespace\", container!=\"\", image!=\"\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Database Size",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "cnpg_pg_database_size_bytes{namespace=\"$namespace\", pod=~\"$instances\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "First Recoverability Point",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(cnpg_collector_first_recoverability_point{namespace=~\"$namespace\",pod=~\"$instances\"})*1000",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 6, "x": 5, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_join(kube_customresource_primary_info{customresource_group=\"postgresql.cnpg.io\", customresource_kind=\"Cluster\", namespace=\"$namespace\",cluster=\"$cluster\"}, \"Primary\", \" ➔ \", \"current_primary\", \"target_primary\") or label_replace(kube_customresource_primary_info{customresource_group=\"postgresql.cnpg.io\", customresource_kind=\"Cluster\", namespace=\"$namespace\",cluster=\"$cluster\"}, \"Primary\", \"$1\", \"current_primary\", \"(.*)\") == label_replace(kube_customresource_primary_info{customresource_group=\"postgresql.cnpg.io\", customresource_kind=\"Cluster\", namespace=\"$namespace\",cluster=\"$cluster\"}, \"Primary\", \"$1\", \"target_primary\", \"(.*)\")",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 5, "x": 11, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_customresource_phase_info{customresource_group=\"postgresql.cnpg.io\", customresource_kind=\"Cluster\", namespace=\"$namespace\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Physical Replication", "type": "text", "gridPos": { "h": 1, "w": 4, "x": 16, "y": 7 } },
  { "title": "Logical Replication", "type": "text", "gridPos": { "h": 1, "w": 4, "x": 20, "y": 7 } },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 6, "x": 5, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_customresource_image_info{customresource_group=\"postgresql.cnpg.io\", customresource_kind=\"Cluster\", namespace=\"$namespace\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 5, "x": 11, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_customresource_phase_info{customresource_group=\"postgresql.cnpg.io\", customresource_kind=\"Cluster\", namespace=\"$namespace\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Replication Lag",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(cnpg_pg_replication_lag{namespace=~\"$namespace\",pod=~\"$instances\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Write Lag",
   "type": "stat",
   "description": "Data sent but not written to the standby's disk",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(cnpg_pg_stat_replication_write_lag_seconds{namespace=~\"$namespace\",pod=~\"$instances\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 20, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(clamp_min(timestamp(cnpg_pg_stat_subscription_last_msg_receipt_time{namespace=\"$namespace\"}) - cnpg_pg_stat_subscription_last_msg_receipt_time{namespace=\"$namespace\"},0))",
     "legendFormat": "Replication Lag"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(abs(cnpg_pg_stat_subscription_received_lsn{namespace=\"$namespace\"} - cnpg_pg_stat_subscription_latest_end_lsn{namespace=\"$namespace\"}))",
     "legendFormat": "LSN Distance"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 11, "x": 5, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (instance)(kube_customresource_instances_status_healthy_info{namespace=\"$namespace\"} or \nkube_customresource_instances_status_replicating_info{namespace=\"$namespace\"}+1 or \nkube_customresource_instances_status_failed_info{namespace=\"$namespace\"}+2)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Replay Lag",
   "type": "stat",
   "description": "Data flushed, but not replayed into the standby database",
   "gridPos": { "h": 2, "w": 2, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(cnpg_pg_stat_replication_replay_lag_seconds{namespace=~\"$namespace\",pod=~\"$instances\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Flush Lag",
   "type": "stat",
   "description": "Data written but not flushed to the standby's disk",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(cnpg_pg_stat_replication_flush_lag_seconds{namespace=~\"$namespace\",pod=~\"$instances\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Evaluation of an SLO objective for logical replication LSN distance to stay below 500MB 99.9% of the time every 7 day rolling period.",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(avg by (subname) (avg_over_time(((abs(cnpg_pg_stat_subscription_received_lsn{namespace=\"$namespace\",worker_type=\"apply\"} - cnpg_pg_stat_subscription_latest_end_lsn{namespace=\"$namespace\"})) < BOOL 500*1024*1024)[$__range:])) * avg by (subname) (avg_over_time((time() - cnpg_pg_stat_subscription_last_msg_receipt_time{namespace=\"$namespace\",worker_type=\"apply\"} < BOOL 120))))",
     "legendFormat": "Logical Replication SLO 99.9% < 500MB"
    }
   ]
  },
  { "title": "Server Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  { "title": "Instance", "type": "text", "gridPos": { "h": 1, "w": 3, "x": 0, "y": 13 } },
  { "title": "Status", "type": "text", "gridPos": { "h": 1, "w": 2, "x": 3, "y": 13 } },
  { "title": "Clustering / replicas", "type": "text", "gridPos": { "h": 1, "w": 3, "x": 5, "y": 13 } },
  { "title": "Zone", "type": "text", "gridPos": { "h": 1, "w": 2, "x": 8, "y": 13 } },
  { "title": "Connections", "type": "text", "gridPos": { "h": 1, "w": 4, "x": 10, "y": 13 } },
  { "title": "Max Connections", "type": "text", "gridPos": { "h": 1, "w": 3, "x": 14, "y": 13 } },
  { "title": "Wraparound", "type": "text", "gridPos": { "h": 1, "w": 3, "x": 17, "y": 13 } },
  { "title": "Started", "type": "text", "gridPos": { "h": 1, "w": 2, "x": 20, "y": 13 } },
  { "title": "Version", "type": "text", "gridPos": { "h": 1, "w": 2, "x": 22, "y": 13 } },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 14 },
   "repeat": "instances",
   "options": {
    "content": "<table style=\"width:100%; height:100%;border:0px solid black;\">\n  <td style=\"text-align: center;vertical-align: middle;border:0px solid black; \"><p style=\"font-weight: bold;\">$instances</p>\n  </td>\n</table>"
   }
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 3, "y": 14 },
   "repeat": "instances",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(kube_pod_container_status_ready{container=\"postgres\",namespace=~\"$namespace\",pod=~\"$instances\"})"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 5, "y": 14 },
   "repeat": "instances",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - cnpg_pg_replication_in_recovery{namespace=~\"$namespace\",pod=~\"$instances\"} + cnpg_pg_replication_is_wal_receiver_up{namespace=~\"$namespace\",pod=~\"$instances\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 1, "x": 7, "y": 14 },
   "repeat": "instances",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cnpg_pg_replication_streaming_replicas{namespace=~\"$namespace\", pod=~\"$instances\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "type": "stat",
   "description": "This metric depends on exporting the: `topology.kubernetes.io/zone` label through kube-state-metrics (not enabled by default). Can be added by changing its configuration with:\n\n```yaml\nmetricLabelsAllowlist:\n  - nodes=[topology.kubernetes.io/zone]\n```",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 14 },
   "repeat": "instances",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_pod_info{namespace=~\"$namespace\", pod=~\"$instances\"} * on(node,instance) group_left(label_topology_kubernetes_io_zone) kube_node_labels",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 14 },
   "repeat": "instances",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pod) (cnpg_backends_total{namespace=~\"$namespace\", pod=~\"$instances\"})",
     "legendFormat": "-"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 3, "w": 3, "x": 14, "y": 14 },
   "repeat": "instances",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 * sum by (pod) (cnpg_backends_total{namespace=~\"$namespace\", pod=~\"$instances\"}) / sum by (pod) (cnpg_pg_settings_setting{name=\"max_connections\", namespace=~\"$namespace\", pod=~\"$instances\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 3, "x": 17, "y": 14 },
   "repeat": "instances",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (pod) (cnpg_pg_database_xid_age{namespace=~\"$namespace\", pod=~\"$instances\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 14 },
   "repeat": "instances",
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cnpg_pg_postmaster_start_time{namespace=~\"$namespace\", pod=~\"$instances\"}*1000"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 14 },
   "repeat": "instances",
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cnpg_collector_postgres_version{namespace=~\"$namespace\", pod=~\"$instances\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Logical Replication", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Subscriptions",
   "type": "table",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "clamp_min(timestamp(cnpg_pg_stat_subscription_last_msg_receipt_time) - cnpg_pg_stat_subscription_last_msg_receipt_time{namespace=\"$namespace\",job=\"$namespace/$cluster\",worker_type=\"apply\"},0)",
     "legendFormat": "__auto"
    },
    {
     "expr": "cnpg_pg_stat_subscription_received_lsn{namespace=\"$namespace\",job=\"$namespace/$cluster\",worker_type=\"apply\"} - cnpg_pg_stat_subscription_latest_end_lsn",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg by (subname) \n(\n    avg by (subname, pod) (\n        last_over_time(\n            avg_over_time(\n                (cnpg_pg_stat_subscription_received_lsn{namespace=\"$namespace\",job=\"$namespace/$cluster\",worker_type=\"apply\"} - cnpg_pg_stat_subscription_latest_end_lsn < bool 500 * 1024 * 1024)[$__range]\n            )[$__interval]\n        )\n    )\n    *\n    avg by (subname, pod) (\n        last_over_time(\n            avg_over_time(\n                (time() - cnpg_pg_stat_subscription_last_msg_receipt_time {namespace=\"$namespace\",job=\"$namespace/$cluster\",worker_type=\"apply\"} < bool 120)[$__range]\n            )[$__interval]\n        )\n    )\n    * \n    on (pod) group_left() (label_replace(kube_customresource_primary_info{customresource_group=\"postgresql.cnpg.io\", customresource_kind=\"Cluster\", namespace=\"$namespace\",cluster=\"$cluster\"}, \"pod\", \"$1\", \"current_primary\", \"(.*)\"))\n)[7d]",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "LSN Distance",
   "type": "timeseries",
   "description": "This shows the LSN distance for each Logical Replication Subscription based on data from `pg_stat_subscription`. Note that in case of replication lag, this value can show LSN distance as 0 when the subscription has not received any new data in a while. Check Last Message Receipt Age to account for that.",
   "gridPos": { "h": 9, "w": 14, "x": 10, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by (subname,worker_type)(max_over_time(cnpg_pg_stat_subscription_received_lsn{namespace=\"$namespace\"} - cnpg_pg_stat_subscription_latest_end_lsn{namespace=\"$namespace\"}))",
     "legendFormat": "{{subname}}"
    }
   ]
  },
  {
   "title": "LSN Distance Growth Rate",
   "type": "timeseries",
   "description": "This shows the LSN rate of change for each Logical Replication Subscription based on data from `pg_stat_subscription`. Note that in case of replication lag, this value can show LSN distance as 0 when the subscription has not received any new data in a while. Check Last Message Receipt Age to account for that.",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "avg by (subname,worker_type)(deriv(cnpg_pg_stat_subscription_received_lsn{namespace=\"$namespace\",job=\"$namespace/$cluster\"} - cnpg_pg_stat_subscription_latest_end_lsn))",
     "legendFormat": "{{subname}} ({{type}})"
    }
   ]
  },
  {
   "title": "Last Message Receipt Age",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 14, "x": 10, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "max by(subname, worker_type) (max_over_time(clamp_min(timestamp(cnpg_pg_stat_subscription_last_msg_receipt_time) - cnpg_pg_stat_subscription_last_msg_receipt_time{namespace=\"$namespace\",job=\"$namespace/$cluster\",worker_type=\"apply\"},0)[$__rate_interval]))*1000",
     "legendFormat": "{{subname}} ({{type}})"
    }
   ]
  },
  {
   "title": "Logical Replication SLO 99.9% < 500MB",
   "type": "timeseries",
   "description": "Evaluation of an SLO objective for logical replication LSN distance to stay below 500MB 99.9% of the time every 7 day rolling period.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg by (subname) (avg_over_time(((abs(cnpg_pg_stat_subscription_received_lsn{namespace=\"$namespace\",worker_type=\"apply\"} - cnpg_pg_stat_subscription_latest_end_lsn{namespace=\"$namespace\"})) < BOOL 500*1024*1024)[$__range:])) * avg by (subname) (avg_over_time((time() - cnpg_pg_stat_subscription_last_msg_receipt_time{namespace=\"$namespace\",worker_type=\"apply\"} < BOOL 120)))",
     "legendFormat": "{{subname}}"
    }
   ]
  },
  { "title": "ParadeDB", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "Segment count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "targets": [
    {
     "expr": "cnpg_paradedb_index_segments_count * on (pod) group_left() (label_replace(kube_customresource_primary_info{customresource_group=\"postgresql.cnpg.io\", customresource_kind=\"Cluster\", namespace=\"$namespace\"}, \"pod\", \"$1\", \"current_primary\", \"(.*)\"))",
     "legendFormat": "{{relname}}"
    }
   ]
  },
  {
   "title": "Segment size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "cnpg_paradedb_index_segments_max_size * on (pod) group_left() (label_replace(kube_customresource_primary_info{customresource_group=\"postgresql.cnpg.io\", customresource_kind=\"Cluster\", namespace=\"$namespace\"}, \"pod\", \"$1\", \"current_primary\", \"(.*)\"))",
     "legendFormat": "max {{relname}}"
    },
    {
     "expr": "cnpg_paradedb_index_segments_avg_size * on (pod) group_left() (label_replace(kube_customresource_primary_info{customresource_group=\"postgresql.cnpg.io\", customresource_kind=\"Cluster\", namespace=\"$namespace\"}, \"pod\", \"$1\", \"current_primary\", \"(.*)\"))",
     "legendFormat": "avg {{relname}}"
    }
   ]
  },
  {
   "title": "$bm25_indicies segments",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 54 },
   "repeat": "bm25_indicies",
   "targets": [
    {
     "expr": "avg(cnpg_paradedb_index_layer_segments_bucket{namespace=\"$namespace\",relname=\"$bm25_indicies\"}) by (le)",
     "legendFormat": "{{relname}}"
    }
   ]
  },
  { "title": "Configuration", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 } },
  { "title": "Instance", "type": "text", "gridPos": { "h": 1, "w": 3, "x": 0, "y": 63 } },
  { "title": "Max Connections", "type": "text", "gridPos": { "h": 1, "w": 3, "x": 3, "y": 63 } },
  { "title": "Shared Buffers", "type": "text", "gridPos": { "h": 1, "w": 3, "x": 6, "y": 63 } },
  { "title": "Effective Cache Size", "type": "text", "gridPos": { "h": 1, "w": 3, "x": 9, "y": 63 } },
  { "title": "Work Mem", "type": "text", "gridPos": { "h": 1, "w": 3, "x": 12, "y": 63 } },
  { "title": "Maintenance Work Mem", "type": "text", "gridPos": { "h": 1, "w": 3, "x": 15, "y": 63 } },
  { "title": "Random Page Cost", "type": "text", "gridPos": { "h": 1, "w": 3, "x": 18, "y": 63 } },
  { "title": "Sequential Page Cost", "type": "text", "gridPos": { "h": 1, "w": 3, "x": 21, "y": 63 } },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 64 },
   "repeat": "instances",
   "options": {
    "content": "<table style=\"width:100%; height:100%;border:0px solid black;\">\n  <td style=\"text-align: center;vertical-align: middle;border:0px solid black; \"><p style=\"font-weight: bold;\">$instances</p>\n  </td>\n</table>"
   }
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 64 },
   "repeat": "instances",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cnpg_pg_settings_setting{name=\"max_connections\",namespace=~\"$namespace\",pod=~\"$instances\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 64 },
   "repeat": "instances",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (pod) (cnpg_pg_settings_setting{name=\"shared_buffers\",namespace=~\"$namespace\",pod=~\"$instances\"}) * max by (pod) (cnpg_pg_settings_setting{name=\"block_size\",namespace=~\"$namespace\",pod=~\"$instances\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 64 },
   "repeat": "instances",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (pod) (cnpg_pg_settings_setting{name=\"effective_cache_size\",namespace=~\"$namespace\",pod=~\"$instances\"}) * max by (pod) (cnpg_pg_settings_setting{name=\"block_size\",namespace=~\"$namespace\",pod=~\"$instances\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 64 },
   "repeat": "instances",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cnpg_pg_settings_setting{name=\"work_mem\",namespace=~\"$namespace\",pod=~\"$instances\"} * 1024",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 64 },
   "repeat": "instances",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cnpg_pg_settings_setting{name=\"maintenance_work_mem\",namespace=~\"$namespace\",pod=~\"$instances\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 64 },
   "repeat": "instances",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cnpg_pg_settings_setting{name=\"random_page_cost\",namespace=~\"$namespace\",pod=~\"$instances\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 64 },
   "repeat": "instances",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cnpg_pg_settings_setting{name=\"seq_page_cost\",namespace=~\"$namespace\",pod=~\"$instances\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Configurations",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 67 },
   "targets": [
    {
     "expr": "cnpg_pg_settings_setting{namespace=~\"$namespace\",pod=~\"$instances\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Operational Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{pod=~\"$instances\", namespace=~\"$namespace\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Usage (container memory working set)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{pod=~\"$instances\", namespace=\"$namespace\", container!=\"\", image!=\"\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Session States",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 84 },
   "targets": [
    {
     "expr": "sum(cnpg_backends_total{namespace=~\"$namespace\",pod=~\"$instances\"}) by (pod)",
     "legendFormat": "total ({{pod}})"
    },
    {
     "expr": "sum(cnpg_backends_total{namespace=~\"$namespace\",pod=~\"$instances\"}) by (state, pod)",
     "legendFormat": "{{state}} ({{pod}})"
    }
   ]
  },
  {
   "title": "Transactions [5m]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 92 },
   "targets": [
    {
     "expr": "sum(rate(cnpg_pg_stat_database_xact_commit{namespace=~\"$namespace\",pod=~\"$instances\"}[5m])) by (pod)",
     "legendFormat": "committed ({{pod}})"
    },
    {
     "expr": "sum(rate(cnpg_pg_stat_database_xact_rollback{namespace=~\"$namespace\",pod=~\"$instances\"}[5m])) by (pod)",
     "legendFormat": "rolled back ({{pod}})"
    }
   ]
  },
  {
   "title": "Longest Transaction",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by (pod) (cnpg_backends_max_tx_duration_seconds{namespace=~\"$namespace\",pod=~\"$instances\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Deadlocks [5m]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 100 },
   "targets": [
    {
     "expr": "rate(cnpg_pg_stat_database_deadlocks{datname=\"\",namespace=~\"$namespace\",pod=~\"$instances\"}[5m])",
     "legendFormat": "count ({{pod}})"
    }
   ]
  },
  {
   "title": "Blocked Queries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 100 },
   "targets": [
    {
     "expr": "cnpg_backends_waiting_total{namespace=~\"$namespace\",pod=~\"$instances\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "PG Stat Activity Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 108 } },
  {
   "title": "Long running queries",
   "type": "heatmap",
   "description": "Number of queries running for longer than 30s",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 109 },
   "targets": [
    {
     "expr": "avg(cnpg_pg_stat_activity_long_running_queries_bucket{namespace=\"$namespace\"}) by (le)",
     "legendFormat": "Count"
    }
   ]
  },
  {
   "title": "Long running queries",
   "type": "timeseries",
   "description": "Number of queries running for longer than 30s",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 109 },
   "targets": [
    {
     "expr": "max(cnpg_pg_stat_activity_long_running_count * on (pod) group_left() (label_replace(kube_customresource_primary_info{customresource_group=\"postgresql.cnpg.io\", customresource_kind=\"Cluster\", namespace=\"$namespace\"}, \"pod\", \"$1\", \"current_primary\", \"(.*)\")))",
     "legendFormat": "Count"
    }
   ]
  },
  {
   "title": "Long running queries duration",
   "type": "timeseries",
   "description": "Age of queries running for longer than 30s",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 109 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(cnpg_pg_stat_activity_long_running_max_duration * on (pod) group_left() (label_replace(kube_customresource_primary_info{customresource_group=\"postgresql.cnpg.io\", customresource_kind=\"Cluster\", namespace=\"$namespace\"}, \"pod\", \"$1\", \"current_primary\", \"(.*)\")))",
     "legendFormat": "Maximum"
    },
    {
     "expr": "max(cnpg_pg_stat_activity_long_running_avg_duration * on (pod) group_left() (label_replace(kube_customresource_primary_info{customresource_group=\"postgresql.cnpg.io\", customresource_kind=\"Cluster\", namespace=\"$namespace\"}, \"pod\", \"$1\", \"current_primary\", \"(.*)\")))",
     "legendFormat": "Average"
    }
   ]
  },
  { "title": "Storage I/O", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 117 } },
  {
   "title": "Database Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 118 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "max by (datname) (cnpg_pg_database_size_bytes{namespace=\"$namespace\", pod=~\"$instances\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Δsize / month",
   "type": "stat",
   "description": "Based on the data from the last 24h",
   "gridPos": { "h": 4, "w": 5, "x": 7, "y": 118 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (datname) (delta( cnpg_pg_database_size_bytes{datname!~\"template.*\", datname!=\"postgres\", namespace=\"$namespace\",job=\"$namespace/$cluster\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Volume Space Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 118 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max by(persistentvolumeclaim, volume) (1 - kubelet_volume_stats_available_bytes{namespace=\"$namespace\", persistentvolumeclaim=~\"$instances.*\"} / kubelet_volume_stats_capacity_bytes * on(namespace, persistentvolumeclaim) group_left(volume,pod) kube_pod_spec_volumes_persistentvolumeclaims_info)",
     "legendFormat": "{{persistentvolumeclaim}} ({{volume}})"
    }
   ]
  },
  {
   "title": "Δsize / month",
   "type": "stat",
   "description": "Based on the data from the last 7d",
   "gridPos": { "h": 4, "w": 5, "x": 7, "y": 122 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (datname) (delta( cnpg_pg_database_size_bytes{datname!~\"template.*\", datname!=\"postgres\", namespace=\"$namespace\",job=\"$namespace/$cluster\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Storage Classes",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 126 },
   "targets": [
    {
     "expr": "kube_persistentvolumeclaim_info{namespace=\"$namespace\"} * on (storageclass) group_left(reclaim_policy, provisioner, volume_binding_mode) kube_storageclass_info",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Volume Inode Usage",
   "type": "timeseries",
   "description": "Represents that Inode usage of your filesystem. Reaching the limit will result in data loss and downtime. This number may be shown as 0.00% even with terrabytes of data on disk which is normal.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 126 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max by(persistentvolumeclaim) (kubelet_volume_stats_inodes_used{namespace=\"$namespace\", persistentvolumeclaim=~\"$instances.*\"} / kubelet_volume_stats_inodes * on(namespace, persistentvolumeclaim) group_left(volume,pod) kube_pod_spec_volumes_persistentvolumeclaims_info)",
     "legendFormat": "{{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "Disk IO (Read)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 134 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(sum by (instance) (node_disk_read_bytes_total) * on(instance) group_left(nodename) node_uname_info) * on(nodename) group_left(pod) label_replace(kube_pod_info{pod=~\"$instances\", namespace=\"$namespace\"}, \"nodename\", \"$1\", \"node\", \"(.*)\")",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Disk IO (Write)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 134 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(sum by (instance) (node_disk_written_bytes_total) * on(instance) group_left(nodename) node_uname_info) * on(nodename) group_left(pod) label_replace(kube_pod_info{pod=~\"$instances\", namespace=\"$namespace\"}, \"nodename\", \"$1\", \"node\", \"(.*)\")",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Disk IOPS",
   "type": "timeseries",
   "description": "Aggregation over large periods of time introduces inaccuracies. Zoom in to periods you are interested in for accurate results.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 142 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max by (customer,instance) (max_over_time(rate(node_disk_reads_completed_total+node_disk_writes_completed_total)[$__rate_interval])[$__interval]) * on(instance,customer) group_left(nodename) node_uname_info{} * on(customer,nodename) group_left(pod) label_replace(kube_pod_info{pod=~\"$cluster-([1-9][0-9]*)$\", namespace=\"$namespace\"}, \"nodename\", \"$1\", \"node\", \"(.*)\")",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Block I/O [5m]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 142 },
   "targets": [
    {
     "expr": "rate(cnpg_pg_stat_database_blks_hit{datname=\"\",namespace=~\"$namespace\",pod=~\"$instances\"}[5m])",
     "legendFormat": "hit ({{pod}})"
    },
    {
     "expr": "rate(cnpg_pg_stat_database_blks_read{datname=\"\",namespace=~\"$namespace\",pod=~\"$instances\"}[5m])",
     "legendFormat": "read ({{pod}})"
    }
   ]
  },
  {
   "title": "Tuple I/O [5m]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 150 },
   "targets": [
    {
     "expr": "sum(rate(cnpg_pg_stat_database_tup_deleted{datname=\"\",namespace=~\"$namespace\",pod=~\"$instances\"}[5m]))",
     "legendFormat": "deleted"
    },
    {
     "expr": "sum(rate(cnpg_pg_stat_database_tup_inserted{datname=\"\",namespace=~\"$namespace\",pod=~\"$instances\"}[5m]))",
     "legendFormat": "inserted"
    },
    {
     "expr": "sum(rate(cnpg_pg_stat_database_tup_fetched{datname=\"\",namespace=~\"$namespace\",pod=~\"$instances\"}[5m]))",
     "legendFormat": "fetched"
    },
    {
     "expr": "sum(rate(cnpg_pg_stat_database_tup_returned{datname=\"\",namespace=~\"$namespace\",pod=~\"$instances\"}[5m]))",
     "legendFormat": "returned"
    },
    {
     "expr": "sum(rate(cnpg_pg_stat_database_tup_updated{datname=\"\",namespace=~\"$namespace\",pod=~\"$instances\"}[5m]))",
     "legendFormat": "updated"
    }
   ]
  },
  {
   "title": "Temp Bytes [5m]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 150 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(cnpg_pg_stat_database_temp_bytes{datname=\"\",namespace=~\"$namespace\",pod=~\"$instances\"}[5m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Network I/O", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 158 } },
  {
   "title": "Network Throughout: $nodes",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 159 },
   "repeat": "nodes",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (node) (rate(container_network_receive_bytes_total{}[$__rate_interval])) * on(node) group_left(pod) kube_pod_info{namespace=~\"$namespace\", pod=~\"$instances\", node=\"$nodes\"}",
     "legendFormat": "{{node}} ({{pod}}) (RX)"
    },
    {
     "expr": "- sum by (node) (rate(container_network_transmit_bytes_total{}[$__rate_interval])) * on(node) group_left(pod) kube_pod_info{namespace=~\"$namespace\", pod=~\"$instances\", node=\"$nodes\"}",
     "legendFormat": "{{node}} ({{pod}}) (TX)"
    }
   ]
  },
  { "title": "Write Ahead Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 169 } },
  {
   "title": "WAL Segment Archive Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 170 },
   "targets": [
    {
     "expr": "cnpg_collector_pg_wal_archive_status{value=\"ready\",namespace=~\"$namespace\",pod=~\"$instances\"}",
     "legendFormat": "ready ({{pod}})"
    },
    {
     "expr": "cnpg_collector_pg_wal_archive_status{value=\"done\",namespace=~\"$namespace\",pod=~\"$instances\"}",
     "legendFormat": "done ({{pod}})"
    }
   ]
  },
  {
   "title": "Archiver Status [5m]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 170 },
   "targets": [
    {
     "expr": "rate(cnpg_pg_stat_archiver_archived_count{namespace=~\"$namespace\",pod=~\"$instances\"}[5m])",
     "legendFormat": "archived ({{pod}})"
    },
    {
     "expr": "rate(cnpg_pg_stat_archiver_failed_count{namespace=~\"$namespace\",pod=~\"$instances\"}[5m])",
     "legendFormat": "failed ({{pod}})"
    }
   ]
  },
  {
   "title": "Last Archive Age",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 170 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "cnpg_pg_stat_archiver_seconds_since_last_archival{namespace=~\"$namespace\",pod=~\"$instances\"}",
     "legendFormat": "age ({{pod}})"
    }
   ]
  },
  {
   "title": "WAL Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 178 },
   "targets": [
    {
     "expr": "cnpg_collector_pg_wal{pod=~\"$instances\", namespace=~\"$namespace\", value=\"count\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Physical Replication", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 186 } },
  {
   "title": "Replication Lag",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 187 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "cnpg_pg_replication_lag{namespace=~\"$namespace\",pod=~\"$instances\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Write Lag",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 187 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "cnpg_pg_stat_replication_write_lag_seconds{namespace=~\"$namespace\",pod=~\"$instances\"}",
     "legendFormat": "{{pod}} -> {{application_name}}"
    }
   ]
  },
  {
   "title": "Flush Lag",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 187 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "cnpg_pg_stat_replication_flush_lag_seconds{namespace=~\"$namespace\",pod=~\"$instances\"}",
     "legendFormat": "{{pod}} -> {{application_name}}"
    }
   ]
  },
  {
   "title": "Replay Lag",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 187 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "cnpg_pg_stat_replication_replay_lag_seconds{namespace=~\"$namespace\",pod=~\"$instances\"}",
     "legendFormat": "{{pod}} -> {{application_name}}"
    }
   ]
  },
  { "title": "Collector Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 195 } },
  {
   "title": "Collection Duration",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 196 },
   "targets": [
    {
     "expr": "cnpg_collector_collection_duration_seconds{namespace=~\"$namespace\",pod=~\"$instances\"}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 196 },
   "targets": [
    {
     "expr": "cnpg_collector_last_collection_error{namespace=~\"$namespace\",pod=~\"$instances\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Backups", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 204 } },
  {
   "title": "First Recoverability Point",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 205 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "targets": [
    {
     "expr": "cnpg_collector_first_recoverability_point{namespace=~\"$namespace\",pod=~\"$instances\"}*1000 > 0",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Checkpoints", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 211 } },
  {
   "title": "Requested/Timed",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 212 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "{__name__=~\"cnpg_pg_stat_(bgwriter|checkpointer)_checkpoints_req\",namespace=~\"$namespace\",pod=~\"$instances\"}",
     "legendFormat": "req/{{pod}}"
    },
    {
     "expr": "{__name__=~\"cnpg_pg_stat_(bgwriter|checkpointer)_checkpoints_timed\",namespace=~\"$namespace\",pod=~\"$instances\"}",
     "legendFormat": "timed/{{pod}}"
    }
   ]
  },
  {
   "title": "Write/Sync time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 212 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "{__name__=~\"cnpg_pg_stat_(bgwriter_checkpoint|checkpointer)_write_time\",namespace=~\"$namespace\",pod=~\"$instances\"}",
     "legendFormat": "write/{{pod}}"
    },
    {
     "expr": "{__name__=~\"cnpg_pg_stat_(bgwriter_checkpoint|checkpointer)_sync_time\",namespace=~\"$namespace\",pod=~\"$instances\"}",
     "legendFormat": "sync/{{pod}}"
    }
   ]
  },
  { "title": "Extensions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 218 } },
  {
   "title": "Installed extensions",
   "type": "table",
   "description": "Show the installed extensions and their versions",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 219 },
   "targets": [
    {
     "expr": "max(cnpg_pg_extensions_update_available{pod=~\"$instances\", namespace=~\"$namespace\"}) by (datname, extname, default_version, installed_version)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Operator", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 227 } },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 228 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_ready{namespace=\"$operatorNamespace\", pod=~\"cloudnative-pg-operator.+\", condition=\"true\"})",
     "legendFormat": "Ready Operator Pods"
    }
   ]
  },
  {
   "type": "stat",
   "description": "The operator reconcile errors don't distinguish between database cluster or namespaces.",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 228 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(controller_runtime_reconcile_total{namespace=~\"$operatorNamespace\", result=\"error\", controller=\"cluster\"})",
     "legendFormat": "Cluster Reconcile Errors"
    }
   ]
  },
  {
   "type": "stat",
   "description": "The operator reconcile errors don't distinguish between database cluster or namespaces.",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 228 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(controller_runtime_reconcile_total{namespace=~\"$operatorNamespace\", result=\"error\", controller=\"backup\"})",
     "legendFormat": "Backup Reconcile Errors"
    }
   ]
  },
  {
   "type": "stat",
   "description": "The operator reconcile errors don't distinguish between database cluster or namespaces.",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 228 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(controller_runtime_reconcile_total{namespace=~\"$operatorNamespace\", result=\"error\", controller=~\"scheduledbackup|scheduled-backup\"})",
     "legendFormat": "Scheduled Backup Reconcile Errors"
    }
   ]
  },
  {
   "type": "stat",
   "description": "The operator reconcile errors don't distinguish between database cluster or namespaces.",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 228 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(controller_runtime_reconcile_total{namespace=~\"$operatorNamespace\", result=\"error\", controller=\"pooler\"})",
     "legendFormat": "Pooler Reconcile Errors"
    }
   ]
  },
  {
   "title": "Ready Operator Pods",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 230 },
   "targets": [
    {
     "expr": "sum(kube_pod_status_ready{namespace=\"$operatorNamespace\", pod=~\"cloudnative-pg-operator.+\", condition=\"true\"})",
     "legendFormat": "Ready Operator Pods"
    }
   ]
  },
  {
   "title": "Cluster Reconcile Errors",
   "type": "timeseries",
   "description": "The operator reconcile errors don't distinguish between database cluster or namespaces.",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 230 },
   "targets": [
    {
     "expr": "max(controller_runtime_reconcile_total{namespace=~\"$operatorNamespace\", result=\"error\", controller=\"cluster\"})",
     "legendFormat": "Cluster Reconcile Errors"
    }
   ]
  },
  {
   "title": "Backup Reconcile Errors",
   "type": "timeseries",
   "description": "The operator reconcile errors don't distinguish between database cluster or namespaces.",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 230 },
   "targets": [
    {
     "expr": "max(controller_runtime_reconcile_total{namespace=~\"$operatorNamespace\", result=\"error\", controller=\"backup\"})",
     "legendFormat": "Backup Reconcile Errors"
    }
   ]
  },
  {
   "title": "Scheduled Backup Reconcile Errors",
   "type": "timeseries",
   "description": "The operator reconcile errors don't distinguish between database cluster or namespaces.",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 230 },
   "targets": [
    {
     "expr": "max(controller_runtime_reconcile_total{namespace=~\"$operatorNamespace\", result=\"error\", controller=~\"scheduledbackup|scheduled-backup\"})",
     "legendFormat": "Scheduled Backup Reconcile Errors"
    }
   ]
  },
  {
   "title": "Pooler Reconcile Errors",
   "type": "timeseries",
   "description": "The operator reconcile errors don't distinguish between database cluster or namespaces.",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 230 },
   "targets": [
    {
     "expr": "max(controller_runtime_reconcile_total{namespace=~\"$operatorNamespace\", result=\"error\", controller=\"pooler\"})",
     "legendFormat": "Pooler Reconcile Errors"
    }
   ]
  }
 ]
}