name: Setup Kind
description: Sets up a kind cluster and installs Helm and kubectl
outputs:
  helm-path:
    description: The path to the Helm binary
    value: ${{ steps.helm.outputs.helm-path }}
  kubectl-path:
    description: The path to the kubectl binary
    value: ${{ steps.kubectl.outputs.kubectl-path }}
runs:
  using: composite
  steps:
    - id: helm
      name: Set up Helm
      uses: azure/setup-helm@9bc31f4ebc9c6b171d7bfbaa5d006ae7abdb4310 # v5.0.1
      with:
        version: v3.21.3

    - id: kubectl
      name: Install kubectl
      uses: azure/setup-kubectl@829323503d1be3d00ca8346e5391ca0b07a9ab0d # v5.1.0

    - name: Create kind cluster
      uses: helm/kind-action@ef37e7f390d99f746eb8b610417061a60e82a6cc # v1.14.0
