name: Setup Kind
description: Sets up a kind cluster and installs Helm and kubectl
outputs:
  helm-path:
    description: The path to the Helm binary
    value: ${{ steps.helm.outputs.helm-path }}
  kubectl-path:
    description: The path to the kubectl binary
    value: ${{ steps.kubectl.outputs.kubectl-path }}
runs:
  using: composite
  steps:
    - id: helm
      name: Set up Helm
      uses: azure/setup-helm@fe7b79cd5ee1e45176fcad797de68ecaf3ca4814 # v4.2.0
      with:
        version: v3.16.2

    - id: kubectl
      name: Install kubectl
      uses: azure/setup-kubectl@901a10e89ea615cf61f57ac05cecdf23e7de06d8 # v3.2

    - name: Create kind cluster
      uses: helm/kind-action@0025e74a8c7512023d06dc019c617aa3cf561fde # v1.10.0
