# workflows/lint-helm.yml
#
# Lint Helm
# Lint Helm Charts using Helm.

name: Lint Helm

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
      - "charts/paradedb/*"
      - ".github/workflows/lint-helm.yml"
  workflow_dispatch:

concurrency:
  group: lint-helm-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  lint-helm:
    name: Lint Helm Charts
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false

    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v4

      - name: Check Helm Formatting
        working-directory: charts/paradedb/
        run: helm lint . --strict
