# Create a tag when a PR on a release/v* branch is merged

name: release-tag

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  tag:
    runs-on: ubuntu-22.04
    steps:
      -
        name: Checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      -
        name: Temporarily disable "include administrators" branch protection
        if: ${{ always() && github.ref == 'refs/heads/main' }}
        id: disable_include_admins
        uses: benjefferies/branch-protection-bot@4b03de4af31ae187c57689946ae340d669c42dd4 # 1.0.8
        with:
          access_token: ${{ secrets.REPO_GHA_PAT }}
          branch: main
          enforce_admins: false
      -
        name: Create tag
        if: github.event.pull_request.merged == true && startsWith(${{ github.head_ref }}, "release/")
        uses: christophebedard/tag-version-commit@ea0363ff76cae3e81c21695cdd21218204be290b # v1.6.3
        with:
          token: ${{ secrets.REPO_GHA_PAT }}
          version_regex: '^Release ([a-z-]+-v[0-9]+\.[0-9]+\.[0-9]+)'
          dry_run: false
      -
        name: Enable "include administrators" branch protection
        uses: benjefferies/branch-protection-bot@4b03de4af31ae187c57689946ae340d669c42dd4 # 1.0.8
        if: ${{ always() && github.ref == 'refs/heads/main' }}
        with:
          access_token: ${{ secrets.REPO_GHA_PAT }}
          branch: main
          enforce_admins: ${{ steps.disable_include_admins.outputs.initial_status }}
