name: test( cluster )

on:
  pull_request:
    branches-ignore:
      - 'gh-pages'

permissions: read-all

jobs:
  test-list:
    runs-on: ubuntu-24.04
    outputs:
      tests: ${{ steps.listTests.outputs.tests }}
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 1
      - id: listTests
        run: |
          echo "tests=$(ls charts/plugin-barman-cloud/test -1 | jq -cRn '{ include: [inputs | { test: "\(.)" }]}')" >> $GITHUB_OUTPUT
  test:
    needs: test-list
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.test-list.outputs.tests) }}
    name: ${{matrix.test}}
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0

      - name: Install Cosign
        uses: sigstore/cosign-installer@d7543c93d881b35a8faa02e8e3605f69b7a1ce62 # v3.10.0

      - name: Setup kind
        uses: ./.github/actions/setup-kind

      - name: Deploy the operator
        uses: ./.github/actions/deploy-operator

      - name: Install cert-manager
        uses: ./.github/actions/deploy-cert-manager

      - name: Install Prometheus CRDs
        run: |
          helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
          helm install prometheus-crds prometheus-community/prometheus-operator-crds

      - name: Install Chainsaw
        uses: kyverno/action-install-chainsaw@6354895e0f99ab23d3e38d85cf5c71b5dc21d727 # v0.2.13
        with:
          verify: true

      - name: Setup MinIO
        run: |
          helm repo add minio-operator https://operator.min.io
          helm upgrade \
            --install \
            --namespace minio-system \
            --create-namespace \
            --wait \
            operator minio-operator/operator
          helm upgrade \
            --install \
            --namespace minio \
            --create-namespace \
            --wait \
            --values ./.github/minio.yaml \
            tenant minio-operator/tenant

      - name: Run Kyverno/Chainsaw
        run: chainsaw test charts/plugin-barman-cloud/test/${{matrix.test}}
